# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/111/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/111/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phoenix/Desktop/LunaLuxEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phoenix/Desktop/LunaLuxEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/111/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/111/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phoenix/Desktop/LunaLuxEngine/CMakeFiles /home/phoenix/Desktop/LunaLuxEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phoenix/Desktop/LunaLuxEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestGame

# Build rule for target.
TestGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestGame
.PHONY : TestGame

# fast build rule for target.
TestGame/fast:
	$(MAKE) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/build
.PHONY : TestGame/fast

#=============================================================================
# Target rules for targets named LunaLuxEngineCore

# Build rule for target.
LunaLuxEngineCore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LunaLuxEngineCore
.PHONY : LunaLuxEngineCore

# fast build rule for target.
LunaLuxEngineCore/fast:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/build
.PHONY : LunaLuxEngineCore/fast

src/Core_src/LunaLuxEngineCore.o: src/Core_src/LunaLuxEngineCore.cpp.o

.PHONY : src/Core_src/LunaLuxEngineCore.o

# target to build an object file
src/Core_src/LunaLuxEngineCore.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/LunaLuxEngineCore.cpp.o
.PHONY : src/Core_src/LunaLuxEngineCore.cpp.o

src/Core_src/LunaLuxEngineCore.i: src/Core_src/LunaLuxEngineCore.cpp.i

.PHONY : src/Core_src/LunaLuxEngineCore.i

# target to preprocess a source file
src/Core_src/LunaLuxEngineCore.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/LunaLuxEngineCore.cpp.i
.PHONY : src/Core_src/LunaLuxEngineCore.cpp.i

src/Core_src/LunaLuxEngineCore.s: src/Core_src/LunaLuxEngineCore.cpp.s

.PHONY : src/Core_src/LunaLuxEngineCore.s

# target to generate assembly for a file
src/Core_src/LunaLuxEngineCore.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/LunaLuxEngineCore.cpp.s
.PHONY : src/Core_src/LunaLuxEngineCore.cpp.s

src/Core_src/common/EnginePanic.o: src/Core_src/common/EnginePanic.cpp.o

.PHONY : src/Core_src/common/EnginePanic.o

# target to build an object file
src/Core_src/common/EnginePanic.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/common/EnginePanic.cpp.o
.PHONY : src/Core_src/common/EnginePanic.cpp.o

src/Core_src/common/EnginePanic.i: src/Core_src/common/EnginePanic.cpp.i

.PHONY : src/Core_src/common/EnginePanic.i

# target to preprocess a source file
src/Core_src/common/EnginePanic.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/common/EnginePanic.cpp.i
.PHONY : src/Core_src/common/EnginePanic.cpp.i

src/Core_src/common/EnginePanic.s: src/Core_src/common/EnginePanic.cpp.s

.PHONY : src/Core_src/common/EnginePanic.s

# target to generate assembly for a file
src/Core_src/common/EnginePanic.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/common/EnginePanic.cpp.s
.PHONY : src/Core_src/common/EnginePanic.cpp.s

src/Core_src/render/Buffer.o: src/Core_src/render/Buffer.cpp.o

.PHONY : src/Core_src/render/Buffer.o

# target to build an object file
src/Core_src/render/Buffer.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Buffer.cpp.o
.PHONY : src/Core_src/render/Buffer.cpp.o

src/Core_src/render/Buffer.i: src/Core_src/render/Buffer.cpp.i

.PHONY : src/Core_src/render/Buffer.i

# target to preprocess a source file
src/Core_src/render/Buffer.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Buffer.cpp.i
.PHONY : src/Core_src/render/Buffer.cpp.i

src/Core_src/render/Buffer.s: src/Core_src/render/Buffer.cpp.s

.PHONY : src/Core_src/render/Buffer.s

# target to generate assembly for a file
src/Core_src/render/Buffer.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Buffer.cpp.s
.PHONY : src/Core_src/render/Buffer.cpp.s

src/Core_src/render/OpenGL/OpenGLBuffer.o: src/Core_src/render/OpenGL/OpenGLBuffer.cpp.o

.PHONY : src/Core_src/render/OpenGL/OpenGLBuffer.o

# target to build an object file
src/Core_src/render/OpenGL/OpenGLBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLBuffer.cpp.o
.PHONY : src/Core_src/render/OpenGL/OpenGLBuffer.cpp.o

src/Core_src/render/OpenGL/OpenGLBuffer.i: src/Core_src/render/OpenGL/OpenGLBuffer.cpp.i

.PHONY : src/Core_src/render/OpenGL/OpenGLBuffer.i

# target to preprocess a source file
src/Core_src/render/OpenGL/OpenGLBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLBuffer.cpp.i
.PHONY : src/Core_src/render/OpenGL/OpenGLBuffer.cpp.i

src/Core_src/render/OpenGL/OpenGLBuffer.s: src/Core_src/render/OpenGL/OpenGLBuffer.cpp.s

.PHONY : src/Core_src/render/OpenGL/OpenGLBuffer.s

# target to generate assembly for a file
src/Core_src/render/OpenGL/OpenGLBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLBuffer.cpp.s
.PHONY : src/Core_src/render/OpenGL/OpenGLBuffer.cpp.s

src/Core_src/render/OpenGL/OpenGLContext.o: src/Core_src/render/OpenGL/OpenGLContext.cpp.o

.PHONY : src/Core_src/render/OpenGL/OpenGLContext.o

# target to build an object file
src/Core_src/render/OpenGL/OpenGLContext.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLContext.cpp.o
.PHONY : src/Core_src/render/OpenGL/OpenGLContext.cpp.o

src/Core_src/render/OpenGL/OpenGLContext.i: src/Core_src/render/OpenGL/OpenGLContext.cpp.i

.PHONY : src/Core_src/render/OpenGL/OpenGLContext.i

# target to preprocess a source file
src/Core_src/render/OpenGL/OpenGLContext.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLContext.cpp.i
.PHONY : src/Core_src/render/OpenGL/OpenGLContext.cpp.i

src/Core_src/render/OpenGL/OpenGLContext.s: src/Core_src/render/OpenGL/OpenGLContext.cpp.s

.PHONY : src/Core_src/render/OpenGL/OpenGLContext.s

# target to generate assembly for a file
src/Core_src/render/OpenGL/OpenGLContext.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLContext.cpp.s
.PHONY : src/Core_src/render/OpenGL/OpenGLContext.cpp.s

src/Core_src/render/OpenGL/OpenGLRenderer.o: src/Core_src/render/OpenGL/OpenGLRenderer.cpp.o

.PHONY : src/Core_src/render/OpenGL/OpenGLRenderer.o

# target to build an object file
src/Core_src/render/OpenGL/OpenGLRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLRenderer.cpp.o
.PHONY : src/Core_src/render/OpenGL/OpenGLRenderer.cpp.o

src/Core_src/render/OpenGL/OpenGLRenderer.i: src/Core_src/render/OpenGL/OpenGLRenderer.cpp.i

.PHONY : src/Core_src/render/OpenGL/OpenGLRenderer.i

# target to preprocess a source file
src/Core_src/render/OpenGL/OpenGLRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLRenderer.cpp.i
.PHONY : src/Core_src/render/OpenGL/OpenGLRenderer.cpp.i

src/Core_src/render/OpenGL/OpenGLRenderer.s: src/Core_src/render/OpenGL/OpenGLRenderer.cpp.s

.PHONY : src/Core_src/render/OpenGL/OpenGLRenderer.s

# target to generate assembly for a file
src/Core_src/render/OpenGL/OpenGLRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLRenderer.cpp.s
.PHONY : src/Core_src/render/OpenGL/OpenGLRenderer.cpp.s

src/Core_src/render/OpenGL/OpenGLShader.o: src/Core_src/render/OpenGL/OpenGLShader.cpp.o

.PHONY : src/Core_src/render/OpenGL/OpenGLShader.o

# target to build an object file
src/Core_src/render/OpenGL/OpenGLShader.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLShader.cpp.o
.PHONY : src/Core_src/render/OpenGL/OpenGLShader.cpp.o

src/Core_src/render/OpenGL/OpenGLShader.i: src/Core_src/render/OpenGL/OpenGLShader.cpp.i

.PHONY : src/Core_src/render/OpenGL/OpenGLShader.i

# target to preprocess a source file
src/Core_src/render/OpenGL/OpenGLShader.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLShader.cpp.i
.PHONY : src/Core_src/render/OpenGL/OpenGLShader.cpp.i

src/Core_src/render/OpenGL/OpenGLShader.s: src/Core_src/render/OpenGL/OpenGLShader.cpp.s

.PHONY : src/Core_src/render/OpenGL/OpenGLShader.s

# target to generate assembly for a file
src/Core_src/render/OpenGL/OpenGLShader.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/OpenGL/OpenGLShader.cpp.s
.PHONY : src/Core_src/render/OpenGL/OpenGLShader.cpp.s

src/Core_src/render/Renderer.o: src/Core_src/render/Renderer.cpp.o

.PHONY : src/Core_src/render/Renderer.o

# target to build an object file
src/Core_src/render/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Renderer.cpp.o
.PHONY : src/Core_src/render/Renderer.cpp.o

src/Core_src/render/Renderer.i: src/Core_src/render/Renderer.cpp.i

.PHONY : src/Core_src/render/Renderer.i

# target to preprocess a source file
src/Core_src/render/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Renderer.cpp.i
.PHONY : src/Core_src/render/Renderer.cpp.i

src/Core_src/render/Renderer.s: src/Core_src/render/Renderer.cpp.s

.PHONY : src/Core_src/render/Renderer.s

# target to generate assembly for a file
src/Core_src/render/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Renderer.cpp.s
.PHONY : src/Core_src/render/Renderer.cpp.s

src/Core_src/render/Shader.o: src/Core_src/render/Shader.cpp.o

.PHONY : src/Core_src/render/Shader.o

# target to build an object file
src/Core_src/render/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Shader.cpp.o
.PHONY : src/Core_src/render/Shader.cpp.o

src/Core_src/render/Shader.i: src/Core_src/render/Shader.cpp.i

.PHONY : src/Core_src/render/Shader.i

# target to preprocess a source file
src/Core_src/render/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Shader.cpp.i
.PHONY : src/Core_src/render/Shader.cpp.i

src/Core_src/render/Shader.s: src/Core_src/render/Shader.cpp.s

.PHONY : src/Core_src/render/Shader.s

# target to generate assembly for a file
src/Core_src/render/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/render/Shader.cpp.s
.PHONY : src/Core_src/render/Shader.cpp.s

src/Core_src/window/Win32Window.o: src/Core_src/window/Win32Window.cpp.o

.PHONY : src/Core_src/window/Win32Window.o

# target to build an object file
src/Core_src/window/Win32Window.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/Win32Window.cpp.o
.PHONY : src/Core_src/window/Win32Window.cpp.o

src/Core_src/window/Win32Window.i: src/Core_src/window/Win32Window.cpp.i

.PHONY : src/Core_src/window/Win32Window.i

# target to preprocess a source file
src/Core_src/window/Win32Window.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/Win32Window.cpp.i
.PHONY : src/Core_src/window/Win32Window.cpp.i

src/Core_src/window/Win32Window.s: src/Core_src/window/Win32Window.cpp.s

.PHONY : src/Core_src/window/Win32Window.s

# target to generate assembly for a file
src/Core_src/window/Win32Window.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/Win32Window.cpp.s
.PHONY : src/Core_src/window/Win32Window.cpp.s

src/Core_src/window/Window.o: src/Core_src/window/Window.cpp.o

.PHONY : src/Core_src/window/Window.o

# target to build an object file
src/Core_src/window/Window.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/Window.cpp.o
.PHONY : src/Core_src/window/Window.cpp.o

src/Core_src/window/Window.i: src/Core_src/window/Window.cpp.i

.PHONY : src/Core_src/window/Window.i

# target to preprocess a source file
src/Core_src/window/Window.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/Window.cpp.i
.PHONY : src/Core_src/window/Window.cpp.i

src/Core_src/window/Window.s: src/Core_src/window/Window.cpp.s

.PHONY : src/Core_src/window/Window.s

# target to generate assembly for a file
src/Core_src/window/Window.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/Window.cpp.s
.PHONY : src/Core_src/window/Window.cpp.s

src/Core_src/window/X11Window.o: src/Core_src/window/X11Window.cpp.o

.PHONY : src/Core_src/window/X11Window.o

# target to build an object file
src/Core_src/window/X11Window.cpp.o:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/X11Window.cpp.o
.PHONY : src/Core_src/window/X11Window.cpp.o

src/Core_src/window/X11Window.i: src/Core_src/window/X11Window.cpp.i

.PHONY : src/Core_src/window/X11Window.i

# target to preprocess a source file
src/Core_src/window/X11Window.cpp.i:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/X11Window.cpp.i
.PHONY : src/Core_src/window/X11Window.cpp.i

src/Core_src/window/X11Window.s: src/Core_src/window/X11Window.cpp.s

.PHONY : src/Core_src/window/X11Window.s

# target to generate assembly for a file
src/Core_src/window/X11Window.cpp.s:
	$(MAKE) -f CMakeFiles/LunaLuxEngineCore.dir/build.make CMakeFiles/LunaLuxEngineCore.dir/src/Core_src/window/X11Window.cpp.s
.PHONY : src/Core_src/window/X11Window.cpp.s

src/Game_src/Game.o: src/Game_src/Game.cpp.o

.PHONY : src/Game_src/Game.o

# target to build an object file
src/Game_src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/src/Game_src/Game.cpp.o
.PHONY : src/Game_src/Game.cpp.o

src/Game_src/Game.i: src/Game_src/Game.cpp.i

.PHONY : src/Game_src/Game.i

# target to preprocess a source file
src/Game_src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/src/Game_src/Game.cpp.i
.PHONY : src/Game_src/Game.cpp.i

src/Game_src/Game.s: src/Game_src/Game.cpp.s

.PHONY : src/Game_src/Game.s

# target to generate assembly for a file
src/Game_src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/src/Game_src/Game.cpp.s
.PHONY : src/Game_src/Game.cpp.s

src/Game_src/main.o: src/Game_src/main.cpp.o

.PHONY : src/Game_src/main.o

# target to build an object file
src/Game_src/main.cpp.o:
	$(MAKE) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/src/Game_src/main.cpp.o
.PHONY : src/Game_src/main.cpp.o

src/Game_src/main.i: src/Game_src/main.cpp.i

.PHONY : src/Game_src/main.i

# target to preprocess a source file
src/Game_src/main.cpp.i:
	$(MAKE) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/src/Game_src/main.cpp.i
.PHONY : src/Game_src/main.cpp.i

src/Game_src/main.s: src/Game_src/main.cpp.s

.PHONY : src/Game_src/main.s

# target to generate assembly for a file
src/Game_src/main.cpp.s:
	$(MAKE) -f CMakeFiles/TestGame.dir/build.make CMakeFiles/TestGame.dir/src/Game_src/main.cpp.s
.PHONY : src/Game_src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TestGame"
	@echo "... LunaLuxEngineCore"
	@echo "... src/Core_src/LunaLuxEngineCore.o"
	@echo "... src/Core_src/LunaLuxEngineCore.i"
	@echo "... src/Core_src/LunaLuxEngineCore.s"
	@echo "... src/Core_src/common/EnginePanic.o"
	@echo "... src/Core_src/common/EnginePanic.i"
	@echo "... src/Core_src/common/EnginePanic.s"
	@echo "... src/Core_src/render/Buffer.o"
	@echo "... src/Core_src/render/Buffer.i"
	@echo "... src/Core_src/render/Buffer.s"
	@echo "... src/Core_src/render/OpenGL/OpenGLBuffer.o"
	@echo "... src/Core_src/render/OpenGL/OpenGLBuffer.i"
	@echo "... src/Core_src/render/OpenGL/OpenGLBuffer.s"
	@echo "... src/Core_src/render/OpenGL/OpenGLContext.o"
	@echo "... src/Core_src/render/OpenGL/OpenGLContext.i"
	@echo "... src/Core_src/render/OpenGL/OpenGLContext.s"
	@echo "... src/Core_src/render/OpenGL/OpenGLRenderer.o"
	@echo "... src/Core_src/render/OpenGL/OpenGLRenderer.i"
	@echo "... src/Core_src/render/OpenGL/OpenGLRenderer.s"
	@echo "... src/Core_src/render/OpenGL/OpenGLShader.o"
	@echo "... src/Core_src/render/OpenGL/OpenGLShader.i"
	@echo "... src/Core_src/render/OpenGL/OpenGLShader.s"
	@echo "... src/Core_src/render/Renderer.o"
	@echo "... src/Core_src/render/Renderer.i"
	@echo "... src/Core_src/render/Renderer.s"
	@echo "... src/Core_src/render/Shader.o"
	@echo "... src/Core_src/render/Shader.i"
	@echo "... src/Core_src/render/Shader.s"
	@echo "... src/Core_src/window/Win32Window.o"
	@echo "... src/Core_src/window/Win32Window.i"
	@echo "... src/Core_src/window/Win32Window.s"
	@echo "... src/Core_src/window/Window.o"
	@echo "... src/Core_src/window/Window.i"
	@echo "... src/Core_src/window/Window.s"
	@echo "... src/Core_src/window/X11Window.o"
	@echo "... src/Core_src/window/X11Window.i"
	@echo "... src/Core_src/window/X11Window.s"
	@echo "... src/Game_src/Game.o"
	@echo "... src/Game_src/Game.i"
	@echo "... src/Game_src/Game.s"
	@echo "... src/Game_src/main.o"
	@echo "... src/Game_src/main.i"
	@echo "... src/Game_src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

