include(${PROJECT_SOURCE_DIR}/CMakeScripts/PhysicsLib.cmake)
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	find_package(Vulkan )
	include_directories(C:/VulkanSDK/1.2.131.1/Include)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
	add_compile_definitions(GLEW_STATIC)
	find_package(Vulkan REQUIRED)
	find_package(X11 REQUIRED)
	link_directories(${X11_LIBRARIES})
endif()
add_library(LunaLuxEngineCoreLib Core_src/LunaLuxEngineCore.cpp Core_src/LunaLuxEngineCore.h Core_src/render/IRender.h Core_src/window/Window.h Core_src/window/Window.cpp Core_src/render/Vulkan.cpp Core_src/render/DirectX.cpp)
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	target_link_libraries(LunaLuxEngineCoreLib LunaLuxEnginePhysicsLib ${VULKAN_LIBRARIES})
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
	target_link_libraries(LunaLuxEngineCoreLib LunaLuxEnginePhysicsLib ${X11_LIBRARIES} ${VULKAN_LIBRARIES})
endif()